# conda environment file for bioblend that you can use to run these tools.
# Create like this:
#   conda env create -f environment.yml
name: bioblend-master
channels:
  - bioconda
dependencies:
  - python=2.7
  - pip:
    - git+https://github.com/galaxyproject/bioblend
